# Generated by Django 3.0.3 on 2020-03-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='postion',
            new_name='position',
        ),
        migrations.AddField(
            model_name='university',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
