# Generated by Django 3.0.3 on 2020-03-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20200303_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='isono',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='repemail',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
