# Generated by Django 3.0.3 on 2020-03-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20200305_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='bio',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='national_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
